### ISSUE TITLE
optionalProperty() and property() don't return what the name suggests

### ISSUE THREAD

**Issue by kevinley** [tentwentyfour/lonad#4]
Currently, `optionalProperty()` returns the actual value, and `property()` returns an Optional Some with the value. 

This should rather be swapped. I expected `property()` to return the value.

**Comment by floriansimon1** [comment]
Already closed?

Both methods return Optionals. OptionalProperty is just a convenient helper to avoid having Some(Some(a)).

Property is property => this.map(x => x[property])

OptionalProperty is the same with a flatmap

**Comment by kevinley** [comment]
Yeah, it’s ok it was me not understanding the Some(Some()) part. 

I used .property().get() now
