### ISSUE TITLE
Order of predicate and lambda in `recoverWhen`

### ISSUE THREAD

**Issue by kwisatz** [tentwentyfour/lonad#7]
The order of evaluation of predicate and lambda (first lambda, then predicate) in `recoverWhen` has tricked me several times. While this can make sense (e.g. to check that applying some algorithm on a given value returns the expected result before continuing), I feel like we could also profit from a function that first runs the predicate (on this.value or this.error, see #6) and only then run the lambda function.

**Comment by floriansimon1** [comment]
This is a bug. We should probably call the predicate before the lambda. Would that break a lot of your code?

**Comment by kwisatz** [comment]
Me personally, I know of just a single occurrence that would be easily fixed. And I just grepped through THE project and there's not a single occurrence of `recoverWhen`. So the answer is probably **no**.
